import { bannerItem } from "../types/banner-item";

export const mockBannerItems: bannerItem[] = [
  {
    id: "1",
    title: "Spend $50, Get $15",
    subtitle: "Limited Time Starbucks Offer",
    image_url: "https://picsum.photos/400/300?random=3",
    category: "discount",
    action_url: "https://starbucks.com/rewards",
    start_date: "2025-07-01",
    end_date: "2025-07-31",
    priority: 1,
    is_active: true,
  },
  {
    id: "2",
    title: "Coffee of the Month: Guava Blend",
    subtitle: "Celebrate tropical flavors this July",
    image_url: "https://picsum.photos/400/300?random=4",
    category: "promotion",
    action_url: "https://example.com/shop/guava-blend",
    start_date: "2025-07-01",
    end_date: "2025-07-31",
    priority: 2,
    is_active: true,
  },
  {
    id: "3",
    title: "New Coffee Scale Now Available",
    subtitle: "Perfect your pour-over game",
    image_url: "https://picsum.photos/400/300?random=7",
    category: "new item",
    action_url: "https://example.com/shop/scale",
    start_date: "2025-07-10",
    end_date: "2025-08-10",
    priority: 3,
    is_active: true,
  },
  {
    id: "4",
    title: "Buy One Get One Free",
    subtitle: "Applicable on all cold brews this weekend",
    image_url: "https://picsum.photos/400/300?random=92",
    category: "discount",
    action_url: "https://example.com/deals/bogo-coldbrew",
    start_date: "2025-07-12",
    end_date: "2025-07-14",
    priority: 4,
    is_active: false, // not active yet or expired
  },
];
