import type { ShopItem } from "../types/shop-item";

export const mockShopItems: ShopItem[] = [
  {
    id: "1",
    name: "Premium Coffee Beans",
    price: 19.99,
    originalPrice: 24.99,
    image: "https://picsum.photos/400/300?random=1",
    category: "beans",
    description: "Aromatic and freshly roasted premium coffee beans.",
    inStock: true,
    rating: 4.8,
    reviews: 120,
    brand: "CoffeeCo",
    features: ["100% Arabica", "Freshly Roasted", "Rich Flavor"],
    specifications: {
      weight: "1lb",
      origin: "Colombia",
    },
  },
  {
    id: "2",
    name: "Barista Espresso Machine",
    price: 249.99,
    image: "https://picsum.photos/400/300?random=7",
    category: "tools",
    description: "Professional-grade espresso machine for home use.",
    inStock: false,
    rating: 4.5,
    reviews: 85,
    brand: "BrewMaster",
    features: ["15-bar pump", "Milk frother", "Compact design"],
    specifications: {
      dimensions: "12x10x8 inches",
      power: "1200W",
    },
  },
  {
    id: "3",
    name: "Gift Card - $50",
    price: 50.0,
    image: "https://picsum.photos/400/300?random=15",
    category: "gift cards",
    description: "The perfect gift for coffee lovers.",
    inStock: true,
    brand: "CoffeeCo",
  },
  {
    id: "4",
    name: "Reusable Coffee Cup",
    price: 14.99,
    originalPrice: 19.99,
    image: "https://picsum.photos/400/300?random=10",
    category: "tools",
    description: "Eco-friendly reusable coffee cup with thermal insulation.",
    inStock: true,
    rating: 4.2,
    reviews: 45,
    brand: "EcoBrew",
    features: ["BPA-free", "Thermal insulation", "Dishwasher safe"],
    specifications: {
      capacity: "16oz",
      material: "Stainless steel",
    },
  },
  {
    id: "5",
    name: "Holiday Blend Coffee Beans",
    price: 22.99,
    image: "https://picsum.photos/400/300?random=21",
    category: "beans",
    description: "Limited edition holiday blend with festive flavors.",
    inStock: true,
    rating: 4.9,
    reviews: 200,
    brand: "CoffeeCo",
    features: ["Seasonal flavors", "Medium roast", "100% Arabica"],
    specifications: {
      weight: "1lb",
      origin: "Ethiopia",
    },
  },
];
